# Generated by Django 3.2.11 on 2022-01-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя тега')),
                ('color', models.CharField(choices=[('#DB4035', 'Красный'), ('#FF9933', 'Оранжевый'), ('#FAD000', 'Желтый'), ('#299438', 'Зелёный'), ('#14AAF5', 'Голубой'), ('#4073FF', 'Синий'), ('#AF38EB', 'Фиолетовый')], max_length=7, unique=True, verbose_name='Цвет')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
            ],
        ),
    ]
