# Generated by Django 3.2.11 on 2022-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#DB4035', 'Красный'), ('#FAD000', 'Желтый'), ('#299438', 'Зелёный'), ('#4073FF', 'Синий'), ('#AF38EB', 'Фиолетовый')], max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
