# Generated by Django 3.2.11 on 2022-01-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
