# Generated by Django 3.2.11 on 2022-01-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220109_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.TextField(max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
