version: '3.3'
services:

  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/.
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile_dev
    volumes:
      - ../frontend/:/app/result_build/

  django:
    build:
      context: ../backend
      dockerfile: Dockerfile_dev

    volumes:
      - ../backend/:/app/
      - media_value:/app/media/

    command: "sh -c 'gunicorn backend.wsgi:application --bind 0.0.0.0:8000'"

    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    restart: always
    depends_on:
      - django
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value: