version: '3.3'
services:

  db:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/.
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile_dev
    volumes:
      - ../frontend/:/app/result_build/

  django:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile_dev

    volumes:
      - ../backend/:/app/
      - media_value:/app/media/

    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    restart: always
    depends_on:
      - django
      - frontend

#  certbot:
#    image: certbot/certbot
#    entrypoint: /bin/sh -c
#    command:
#      - sleep 10000
##    command:
##      - certbot certonly --manual --preferred-challenges dns --agree-tos -m borisov_aleks@mail.ru -d foodgram-aybor.tk && mv /etc/letsencrypt/archive/* /certs
#    volumes:
#      - ./certs:/certs

volumes:
  postgres_data:
  static_value:
  media_value: